api/urls.py
from django.urls import path
from . import views
#Set urls here

app_name = "api"
urlpatterns = [
    path('', views.ArticlesList.as_view(), name="api_view"),
    path('<int:pk>', views.ArticlesDetail.as_view(), name="detail_api_view"),
    path('users/', views.UserList.as_view(), name="list_view_user"),
    path('users/<int:pk>', views.UserDetail.as_view(), name="detail_view_user"),
    path('users/<int:pk>/create', views.UserDetailCreate.as_view(), name="detail_create_view_user"),
]

articles/urls.py
from django.urls import path, include
from . import views
#Set urls for /articles here
app_name = "articles"
urlpatterns = [
    path("", views.ArticlesList.as_view(), name="home"),
    path("page/<int:page>", views.ArticlesList.as_view(), name="home"),
    path('details/<slug:slug>', views.ArticleDetail.as_view(), name="details"),
    path('preview/<int:pk>', views.ArticlePreview.as_view(), name="preview"),
    path('category/<slug:slug>', views.category_articles, name="category"),
    path('search/', views.SearchList.as_view(), name="search"),
    path('search/page/<int:page>', views.SearchList.as_view(), name="search"),
]

myweblog/urls.py
from django.contrib import admin
from django.urls import path, include
from account.views import Login, Register, activate

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', Login.as_view(), name='login'),
    path('login/', Login.as_view(), name='login'),
    path('register/', Register.as_view(), name='register'),
    path('activate/<uidb64>/<token>/', activate, name='activate'),    
    path(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
    path('', include('articles.urls')),
    path('', include('django.contrib.auth.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls')),
    path('account/', include('account.urls')),
    path('comment/', include('comment.urls')),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from myweblog import settings
from extends.jtime import jalali_convertor
from django.utils.html import format_html
from account.models import User
from django.contrib.contenttypes.fields import GenericRelation
from comment.models import Comment
from star_ratings.models import Rating, UserRating


class ArticlesManager(models.Manager):
    def published(self):
        return self.filter(status="p")
    

class CategoryManager(models.Manager):
    def active(self):
        return self.filter(status=True)
# Create your models here.
class IPAddress(models.Model):
    ip_address = models.GenericIPAddressField(verbose_name="آدرس آی پی")

    class Meta:
        verbose_name = "نشانی آی پی"
        verbose_name_plural = "نشانی های آی پی"

class Category(models.Model):
    title = models.CharField(max_length=100, verbose_name="عنوان")
    parent = models.ForeignKey('self', on_delete=models.SET_NULL, related_name="children", verbose_name="زیردسته", null=True, blank=True)
    slug = models.SlugField(max_length=100, unique=True, verbose_name="آدرس")
    status = models.BooleanField(default=True, verbose_name="آیا نشان داده شود؟")
    position = models.IntegerField(verbose_name="جایگاه")

    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"
        ordering = ['parent__id', 'position']

    def __str__(self):
        return self.title

    objects = CategoryManager()



class Articles(models.Model):
    STATUS_CHOICES = [
        ('p', 'منتشرشده'),
        ('d', 'پیش نویس'),
        ('i', 'در حال بررسی'),
        ('b', 'برگشت داده شده'),
    ]

    title = models.CharField(max_length=200, verbose_name="عنوان")
    slug = models.SlugField(max_length=100, unique=True, verbose_name="آدرس مقاله")
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="نویسنده")
    description = models.TextField(verbose_name="متن")
    thumbnail = models.ImageField(upload_to="Images", null=True, verbose_name="تصویر")
    publish = models.DateTimeField(default=timezone.now, verbose_name="زمان انتشار")
    create = models.DateTimeField(auto_now_add=True, verbose_name="زمان نوشتار")
    update = models.DateTimeField(auto_now=True, verbose_name="زمان بروزرسانی")
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, verbose_name="وضعیت")
    is_special = models.BooleanField(default=False, verbose_name="مقاله ویژه")
    category = models.ManyToManyField(Category, verbose_name="دسته یندی", related_name="articles")
    comments = GenericRelation(Comment)
    ratings = GenericRelation(Rating, related_query_name='articles')
    hits = models.ManyToManyField(IPAddress, through="ArticleHit", related_name="hits", blank=True, verbose_name="بازدید ها")
    class Meta:
        verbose_name="مقاله"
        verbose_name_plural="مقالات"

    def jpublish(self):
        return jalali_convertor(self.publish)
    jpublish.short_description = "زمان انتشار"

    def category_publish(self):
        return self.category.filter(status=True)

    objects = ArticlesManager()

    def __str__(self):
        return self.title
        
    def thumbnail_tag(self):
        return format_html("<img width=100 height=75 style='border-radius: 5px;' src='{}' >".format(self.thumbnail.url))

    thumbnail_tag.short_description = "عکس"

    def category_to_str(self):
        return ", ".join([ category.title for category in self.category_publish()])
    category_to_str.short_description = "دسته یندی ها"

    def get_absolute_url(self):
        return reverse("account:home")

class ArticleHit(models.Model):
    article = models.ForeignKey(Articles, on_delete=models.CASCADE)
    ip_address = models.ForeignKey(IPAddress, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

articles/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Articles, Category
from django.views.generic.list import ListView
from django.core.paginator import Paginator
from django.views.generic.detail import DetailView
from account.mixins import AuthorAccessMixin
from django.db.models import Count, Q
from datetime import datetime, timedelta

#Create your views here

# def home(request, page=1):
#     articles_list = Articles.objects.published()
#     paginator = Paginator(articles_list, 2)
#     articles = paginator.get_page(page)
#     content = {
#         "articles": articles
#     }
#     return render(request, 'articles/articles_list.html', content)

class ArticlesList(ListView):
    model = Articles
    #context_object_name = "articles"
    queryset = Articles.objects.published()
    paginate_by = 2

# def details(request, slug):
#     content = {
#         "article": get_object_or_404(Articles, slug=slug)
#     }
#     return render(request, 'articles/single.html', content)

class ArticleDetail(DetailView):

    context_object_name = "article"

    def get_object(self):
        slug = self.kwargs.get("slug")
        article = get_object_or_404(Articles.objects.published(), slug=slug)

        ip_address = self.request.user.ip_address
        if ip_address not in article.hits.all():
            article.hits.add(ip_address)


        return article

class ArticlePreview(AuthorAccessMixin, DetailView):

    context_object_name = "article"

    def get_object(self):
        pk = self.kwargs.get("pk")
        return get_object_or_404(Articles, pk=pk)


def category_articles(request, slug):
    category = get_object_or_404(Category, slug=slug, status=True)
    articles = category.articles.published()
    content = {
        "articles": articles
    }
    return render(request, 'articles/category.html', content)



class SearchList(ListView):
    template_name = "articles/search_list.html"
    paginate_by = 2

    def get_queryset(self):
        search = self.request.GET.get('q')
        return Articles.objects.filter(Q(description__icontains=search) | Q(title__icontains=search))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search'] = self.request.GET.get('q')
        return context

templates/articles/partials/category_loop.html
<ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
  {% for cat in cat.children.active %}
  <li class="dropdown-submenu">
    <a class="dropdown-item dropdown-toggle" role="button" href="{% url 'articles:category' cat.slug   %}">
      {{ cat.title}}</a>
    {% if cat.children.active %} {% include 'articles/partials/category_loop.html' %}
    {% endif %}
  </li>
  {% endfor %}
</ul>

templates/articles/partials/navbar_category.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="container px-4 px-lg-5 collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link"  href="{% url 'articles:home' %}">Home</a>
      </li>
      {% for cat in category %} {% if cat.parent == None %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" role="button" id="navbarDropdownMenuLink"
          href="{% url 'articles:category' cat.slug   %}">
          {{ cat.title }}</a>
        {% if cat.children.active %} {% include 'articles/partials/category_loop.html' %}
        {% endif %}
        {% endif %} {% endfor %}
      </li>
    </ul>
  </div>
  <!-- search secion -->
  <form class="form-inline" action="{% url 'articles:search' %}">
    <button class="btn btn-success" style="padding: 8px; border-radius: 5px; margin-right: 10px;">جست و جو</button>
    <input type="text" name="q" style="direction: rtl; margin-right: 10px;" placeholder="جست و جو...">
  </form>
  <!-- search secion -->
</nav>






<!-- <div class="collapse navbar-collapse" id="navbarResponsive">
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'articles:home' %}">خانه</a>
    </li>
    {% for cat in category %} {% if cat.parent == None %}
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" role="button" id="navbarDropdownMenuLink"
        href="{% url 'articles:category' cat.slug   %}">
        {{ cat.title }}</a>
      {% if cat.children.active %} {% include 'articles/partials/category_loop.html' %}
      {% endif %}
    </li>
    {% endif %} {% endfor %}
  </ul>
</div> -->

templates/articles/partials/popular_articles.html
<div class="container px-4 px-lg-5 my-5">
	<div class="populate_articles_box">
		<h1 class="h4">
			مقالات پر بازدید
		</h1>
		<hr>

		{% for a in popular_articles %}
		<div>
			<a href="{% url 'articles:details' a.slug %}">{{ a.title }}</a>
		</div>
		{% endfor %}
	</div>
</div>
<style type="text/css">
	.populate_articles_box {
	    border: 1px solid #ccc;
	    padding: 15px;
	    margin-bottom: 2rem;
	    font-family: Vazir;
	}
</style>

templates/articles/partials/sidebar.html
<div class="container px-4 px-lg-5 my-5">
	<div class="populate_articles_box">
		<h1 class="h4">
			{{ title }}
		</h1>
		<hr>

		{% for a in articles %}
		<div>
			<a href="{% url 'articles:details' a.slug %}">{{ a.title }}</a>
		</div>
		{% endfor %}
	</div>
</div>
<style type="text/css">
	.populate_articles_box {
	    border: 1px solid #ccc;
	    padding: 15px;
	    margin-bottom: 2rem;
	    font-family: Vazir;
	}
</style>